name: Mutation tests

on:
    push:
        paths:
            - '**workflows/mutation-tests.yml'
            - '**.php'
            - '**composer.json'
            - '**infection.json5.dist'
            - '**phpunit.xml.dist'
    pull_request:
        paths:
            - '**workflows/mutation-tests.yml'
            - '**.php'
            - '**composer.json'
            - '**infection.json5.dist'
            - '**phpunit.xml.dist'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    mutation-tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    tools: infection
            -   uses: ramsey/composer-install@v3
            -   run: infection --min-covered-msi=95 --no-progress --log-verbosity=none --threads=max