name: Static analysis

on:
    push:
        paths:
            - '**workflows/static-analysis.yml'
            - '**.php'
            - '**composer.json'
            - '**phpcs.xml.dist'
            - '**psalm.xml'
    pull_request:
        paths:
            - '**workflows/static-analysis.yml'
            - '**.php'
            - '**composer.json'
            - '**phpcs.xml.dist'
            - '**psalm.xml'
    workflow_dispatch:
        inputs:
            jobs:
                required: true
                type: choice
                default: 'Run all'
                description: 'Choose jobs to run'
                options:
                    - 'Run all'
                    - 'Run PHPCS only'
                    - 'Run Psalm only'
                    - 'Run lint only'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint-php:
        uses: inpsyde/reusable-workflows/.github/workflows/lint-php.yml@main
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') || (github.event.inputs.jobs == 'Run lint only')) }}
        strategy:
            fail-fast: false
            matrix:
                php-ver: [ '8.3', '8.4' ]
        with:
            PHP_VERSION: ${{ matrix.php-ver }}

    coding-standards-analysis-php:
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') && (github.event.inputs.jobs == 'Run PHPCS only')) }}
        uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main

    static-code-analysis-php:
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') && (github.event.inputs.jobs == 'Run Psalm only')) }}
        uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
        strategy:
            fail-fast: false
            matrix:
                php-ver: [ '8.3' ]
        with:
            PHP_VERSION: ${{ matrix.php-ver }}
